GET http://localhost:5000/users

###
GET http://localhost:5000/users/6537365bf7a16632af530111

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "testing",
    "email" : "test@gmail.com",
    "gender" : "Male"
}

###
PATCH http://localhost:5000/users/6537365bf7a16632af530111
Content-Type: application/json

{
    "name": "iwan purwadi"
}

###
DELETE http://localhost:5000/users/653de982ce31219d96aa9dc6